---
title: "LFTP Guide"
author: "Nick Hoffman"
date: "October 2024"
output:
  html_document:
    df_print: paged
    highlight: pygment
    keep_md: no
    toc: true
    number_sections: true
    toc_depth: 1
    toc_float: true
    theme: journal
editor_options:
    chunk_output_type: inline
---

<style type="text/css">
h2, h3, h4, h5, h6 {
  counter-reset: section;
}
p {
  font-size:18px;
}

ul {
  font-size:18px;
}

li {
  font-size:18px;
}
table {
   padding: 0;border-collapse: collapse;
   layout: fixed;
   width: 90%; }
table tr {
   border-top: 1px solid #cccccc;
   background-color: white;
   margin: 0;
   padding: 0; }
table tr:nth-child(2n) {
   background-color: #f8f8f8; }
table tr th {
   font-weight: bold;
   border: 1px solid #cccccc;
   margin: 0;
   padding: 6px 13px; }
table tr td {
   border: 1px solid #cccccc;
   margin: 0;
   padding: 6px 13px; }
table tr th :first-child, table tr td :first-child {
   margin-top: 0; }
table tr th :last-child, table tr td :last-child {
   margin-bottom: 0; }
.html-widget {
    margin: auto;
}
</style>

---

# Introduction

This guide will provide resources for using LFTP, a command-line FTP client. This will be particularly useful if you want to automate file transfers from a cluster by submitting jobs.

# What is L/FTP?

FTP stands for File Transfer Protocol. It is a protocol for sending files across networked computers (e.g., the internet). LFTP is a particular software that enables use of FTP as well as several other tranfer protocols (SFTP, FTPS, HTTP, HTTPS...) through the command line.

# Why use LFTP?

LFTP is particularly useful for transferring files from a high-performance computing cluster (HPCC) to our server because it accepts a user's password in the command itself. That is, it doesn't require interactive input of one's password. That makes it easy to automate.

# LFTP bash script template

[This file](lftp.sh) is a template for a bash script that you can submit to your cluster in order to automate file transfers through SFTP. It was provided by Younghwan Kwak.

Make sure, when using this template, to update the following information:

1. our server's actual IP address (FTP_SERVER="sftp://1.2.3.4" - replace 1.2.3.4 with the correct IP address)
2. your username for the server
3. your password for the server
4. the path to the server directory where you'd like to store your files (e.g., "/data/Squid/theme2/dna/exp1")
5. the actual names of the files that you want to transfer as given in the local cluster directory, and optionally
6. your email address in the SBATCH specifications at the top, to be kept updated on the status of your job.

Lastly, if you're submitting this job to a cluster other than UC-Merced's PINNACLES, you may need to change the name of the partition to which you're submitting the job in the SBATCH specifications.
